language: node_js
node_js:
    - "0.10"

before_script:
    - npm install -g grunt-cli@0.1.x
    - npm install -g mocha
    - npm install -g istanbul

    - cd server
    - npm install --quiet
    - node server.js &
    - sleep 3
    - cd ../client
    - npm install --quiet
    - grunt
    - cd ..

services:
    - mongodb

script:
    - grunt --gruntfile client/gruntfile.js
    - grunt --gruntfile server/gruntfile.js
    #- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    #- istanbul cover ./server/node_modules/mocha/bin/_mocha ./server/test --recursive --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./server/node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - cd server && istanbul cover ./node_modules/mocha/bin/_mocha test/**/*.js --recursive --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
